name: Build and Release Tokens Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Run tokens.transform
        run: npm run tokens.transform

      - name: Run tokens.build
        run: npm run tokens.build

      - name: Publish package to GitHub Packages
        uses: guillaumearm/github-push-action@v1.2.2
        with:
          directory: "build"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          tag: ${{ github.ref }}
          tag_name: "v${{ env.npm_package_version }}"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_message: "Release v${{ env.npm_package_version }}"
